trigger:
- main  # Update to the branch you want to trigger the pipeline

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'Use_Case7'  # Name of the Azure service connection
  resourceGroupName: 'myresourcegroup'  # The name of the Azure Resource Group
  appName: 'dot-net-webapp'  # The name of the Azure Web App
  location: 'East US'  # Azure region
  

stages:
- stage: Deploy
  jobs:
  - job: DeployWebApp
    steps:
    - task: AzurePowerShell@5
      inputs:
        azureSubscription: $(azureSubscription)
        ScriptPath: './deploy-azure-webapp.ps1'
        ScriptArguments: '-ResourceGroupName $(resourceGroupName) -AppName $(appName) -Location $(location)'
        azurePowerShellVersion: 'LatestVersion'
        pwsh: true
